# Introduction to Machine Learning: Penalized Linear Regressions
---
## Why Machine Learning?
### Two Cultures in Using Statistical Modeling 
> There are two cultures in the use of statistical
modeling to reach conclusions from data. One assumes that the data
are generated by a given stochastic data model. The other uses algorithmic
models and treats the data mechanism as unknown.
 ......
If our goal as a field is to use data to solve problems, then
we need to move away from exclusive dependence on data models and
adopt a more diverse set of tools.~ ``Breiman [2001], p199``.

* **Machine learning (ML) methods** are beginning to be widely used in empirical
works by economists, though in a much slower pace than in statistics
* Traditional econometrics emphasizes the use of methods with *formal properties*, while ML methods emphasizes *algorithms* 
* Econometricians are stepping into the territory of ML, fostering the interaction between the two fields

### What is Machine Learning?
Consider the regression model:
$$
y=\mathbf{x}'\boldsymbol{\beta}+\epsilon,\quad \epsilon \perp \mathbf{x}
$$
where $\mathbf{x}$ is a $p$-dimensional, sample size is $n$. 
* *High-dimensional* setting: $p\gg n$
* **Machine Learning** :the *computer (machine)* **learns**
the model $\hat{f}\left(\textbf{x}\right)$ from the data

* Methods of *Machine Learning*: 
  * Supervised Learning: *Regression* (continuous outcome) and *Classification* (binary outcome)
  * Unsupervised Learning: *Clustering* (grouping similar observations) 

### Econometrics vs. Machine Learning 

| **Tools** | `Econometrics` | `Machine Learning` |
|:---------:|:------------------:|:------------------:|
|**General** | Model-based | Algorithmic |
|**Goals**  | Estimates and Inference | Prediction & Classification |
| | $\beta_{ols}=argmin_{\beta}\sum_{i=1}^N(Y_i-\mathbf{X}_i'\boldsymbol{\beta})^2$ | $min_{\beta}\sum_{j=N+1}^{N_m} (Y_j-\hat{Y}_j)^2$ |
|**Terminology** |(estimation) sample| training/test(hold-out) sample |
| |regressors, covariates, or predictors|features|
| |prediction | supervised learning, unsupervised learning, deep learning, or reinforcement learning, etc.|
|**Methods**| Estimating parameters in a given model | Cross-validation: predictive power vs. out-of-sample comparison|
## Penalized Linear Regressions
* When the number of regressors $p$ is large relative to the number of observations $n$, we call it *high-dimensional setting* 
  
* **High-dimensional setting** arises when 
  * data have large dimensional features (i.e. many covariates  are available for use as regressors)
  * we construct many technical regressors1 from raw regressors
  
* In this case, we need to use *penalized linear regressions* to avoid overfitting and to select important regressors
* The basic idea is to add a penalty term to the least squares objective function


### Approximate Sparse Regression Coefficients (近似稀疏回归系数)

> **Approximate sparsity**: 第$j$个最大回归系数$|\beta|_{(j)}$满足: $$|\beta|_{(j)}\leq Aj^{-a}, a >0.5$$

  * 假设真实的回归系数向量虽然在严格意义上并非完全为零，但其绝对值经过排序后会快速衰减，使得使用有限个最重要的自变量就能很好地近似原回归函数

![image.png](attachment:image.png)

### Lasso Regression 

* **Overfitting** problem: Using patterns in the sample and do not generalize out of sample 
  * Good or even perfect fit in sample, but poor out of sample prediction
  * Happens when $p$ is large relative to $n$
* **Lasso** constructs $\hat{\beta}$ as the solution to the following optimization problem:
  >  *Lasso regression problem*: $$ \min_{b\in \mathbb{R}^p} \sum_{i=1}^n (Y_i - b\mathbf{X}_i')^2 + \lambda \cdot \sum_{j=1}^p |b_j|\hat{\psi}_j $$
    * First term is the OLS objective function
    * Second term is the penalty term: $\hat{\psi}$(*penalty loadings*), $\lambda$ (*penalty level*)
* The *penalty loadings* are typically set as:
   $$
   \hat{\psi}_j = \sqrt{\frac{1}{n}\sum_{i=1}^n X_{ij}^2}
   $$
   * When the regressors are *centered*, $X = X^{raw}-E_n(X^{raw})$
   * When the regressors are *normalized*, $E[X_j^2]=1$, then $\hat{\psi}_j=1$ 
   * Many software packages automatically *standardize (centering + normalization)* the regressors

* **The Function of $\lambda$**:
  * The term $\sum_{j=1}^p |b_j|\hat{\psi}_j$ is a measure of **complexity** of the model 
  * When $\lambda > 0$, solving the Lasso problem trading off **in-sample fit** and model **complexity**
  * The Lasso solution *shrinks some coefficients of the regressors towards zero.*

* **Features of Lasso**: 
  > 1. The penalty term help avoids *overfitting*: a wise choice of $\lambda$ can approximate the optimal predictor 
  > 2. Lasso does *variable selection* based on the marginal benefit of *predictive ability*:
    >  *  **Marginal cost** of adding $X_j$ is $\lambda \hat{\psi}_j$ 
    > * Drops variables (sets $b_j=0$) with marginal cost larger than marginal benefit 
* **Choice of $\lambda$ in Lasso**:
  A theoretically valid choice is
    $$
    \lambda = 2\cdot c\hat{\sigma} \sqrt{n}z_{1-\frac{a}{2p}} \leq 2\cdot c\hat{\sigma} \sqrt{2nlog(2p/a)}
    $$
    * $\hat{\sigma}\approx \sigma = \sqrt{E[\epsilon^2]}$ is obtained using iteration method 
    * $1-a$ is the confidence level 
    * **Practical Recommendation**: $c=1.1$, $a=0.05$
### OLS Post-Lasso 

>  **Post-Lasso**: $$ \beta^{post-lasso} = \arg\min_{\beta} \sum_{i=1}^n (Y_i - \beta'\mathbf{X}_i')^2$$ such that $b_j =0$ if $\hat{\beta}_j^{lasso}=0$ 

* Refit the model using Lasso-selected variables by OLS 
  
* By removing the penalty term that causes shrinkage towards zero, it can improve the predictive performance 

## Other Penalized Regression Methods 
### 1. Ridge Regression
> **Ridge Regression**: $$ \hat{\beta}^{ridge}(\lambda) = \arg\min_{b} \sum_{i=1}^n (Y_i - b'\mathbf{X}_i')^2 + \lambda \cdot \sum_{j=1}^p b_j^2$$
  * In contrast to Lasso, Ridge penalizes the large values of  coefficients much more aggressively and small values much  less aggressively 
  * Ridge does not set estimated coefficients to zero and  so it does not do variable selection
  * When to use **Ridge**?
    * "Dense" models where all $\beta_j$'s are all small 
    * Matrix $E(XX')$ is poorly behaved (un-invertible, zero eigenvalues)
### 2. Elastic Net

> **Elastic Net**: $$ \hat{\beta}^{elastic net}(\lambda_1,\lambda_2) = \arg\min_{\beta} \sum_{i=1}^n (Y_i - \beta'\mathbf{X}_i')^2 + \lambda_1 \cdot \sum_{j=1}^p b_j^2 + \lambda_2 \cdot \sum_{j=1}^p |b_j|$$
  * A combination of Lasso and Ridge to have more flexibility for better prediction 
  * Performs variable selection unless $\lambda_2 = 0$ 
  * Can handle both the case of either approximated sparse or dense coefficients. 
### 3. Lava

> **Lava**: $$ \hat{\beta}^{lava}(\lambda_1, \lambda_2) = \arg\min_{\beta: \beta= \delta + \xi} \sum_{i=1}^n (Y_i - \beta'\mathbf{X}_i')^2 + \lambda_1 \cdot \sum_{j=1}^p \delta _j^2 + \lambda_2 \cdot \sum_{j=1}^p |\xi_j|$$
  * A combination of Lasso and Ridge to have more flexibility for better prediction 
  * Performs variable selection 
  * Work well in "sparse + dense" models 
  * Large $\lambda_1$ for "sparse" models and large $\lambda_2$ for "dense" models 
## Practical Choice of Regression Methods 

* If the goal is to get the **best prediction**:
  
  * Spilt the data into training and testing sets, choose the best method using cross-validation 
  
  * Let's work on an example of these methods using `Python` 
## Example: Predicting Wages 

**Our problem**: How to use job-relevant characteristics, such as education and experience, to best predict wages?

### Dataset 

The data set we consider is from the March Supplement of the U.S. Current Population Survey, year 2015. 
* The dependent variable of interest is the (log) hourly wage 
* Final sample size is $n=5150$

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import sklearn.linear_model as lm
import statsmodels.formula.api as smf
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import warnings
# ignore potential convergence warnings; for some small penalty levels,
# tried out, optimization might not converge
warnings.simplefilter('ignore')

In [ ]:
#load the dataset and describe it
file = "https://raw.githubusercontent.com/CausalAIBook/MetricsMLNotebooks/main/data/wage2015_subsample_inference.csv"
df = pd.read_csv(file)
df.describe()

,wage,lwage,sex,shs,hsg,scl,clg,ad,mw,so,we,ne,exp1,exp2,exp3,exp4,occ,occ2,ind,ind2
count,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000
mean,23.410410,2.970787,0.444466,0.023301,0.243883,0.278058,0.317670,0.137087,0.259612,0.296505,0.216117,0.227767,13.760583,3.018925,8.235867,25.118038,5310.737476,11.670874,6629.154951,13.316893
std,21.003016,0.570385,0.496955,0.150872,0.429465,0.448086,0.465616,0.343973,0.438464,0.456761,0.411635,0.419432,10.609465,4.000904,14.488962,53.530225,11874.356080,6.966684,5333.443992,5.701019
min,3.021978,1.105912,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,370.000000,2.000000
25%,13.461538,2.599837,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.250000,0.125000,0.062500,1740.000000,5.000000,4880.000000,9.000000
50%,19.230769,2.956512,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,1.000000,1.000000,4040.000000,13.000000,7370.000000,14.000000
75%,27.777778,3.324236,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,21.000000,4.410000,9.261000,19.448100,5610.000000,17.000000,8190.000000,18.000000
max,528.845673,6.270697,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,47.000000,22.090000,103.823000,487.968100,100000.000000,22.000000,100000.000000,22.000000

In [ ]:
#Construct Variables 
Y = np.log(df['wage'])
Z = df.drop(['wage', 'lwage'], axis=1)
print(Z.shape)
Z.describe() # to print it into latex, print(Z.describe().to_latex())

(5150, 18)

,sex,shs,hsg,scl,clg,ad,mw,so,we,ne,exp1,exp2,exp3,exp4,occ,occ2,ind,ind2
count,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000,5150.000000
mean,0.444466,0.023301,0.243883,0.278058,0.317670,0.137087,0.259612,0.296505,0.216117,0.227767,13.760583,3.018925,8.235867,25.118038,5310.737476,11.670874,6629.154951,13.316893
std,0.496955,0.150872,0.429465,0.448086,0.465616,0.343973,0.438464,0.456761,0.411635,0.419432,10.609465,4.000904,14.488962,53.530225,11874.356080,6.966684,5333.443992,5.701019
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,370.000000,2.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.250000,0.125000,0.062500,1740.000000,5.000000,4880.000000,9.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,1.000000,1.000000,4040.000000,13.000000,7370.000000,14.000000
75%,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,21.000000,4.410000,9.261000,19.448100,5610.000000,17.000000,8190.000000,18.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,47.000000,22.090000,103.823000,487.968100,100000.000000,22.000000,100000.000000,22.000000

### Prediction Question
Now, we will construct a prediction rule for hourly (log) wage  $Y$, which depends linearly on job-relevant characteristics  $X$:

$$
Y=\beta'X+𝜖.
$$

Our goals are
* Predict wages using various characteristics of workers.
* Assess the predictive performance of a given model using the (adjusted) sample MSE, the (adjusted) sample $R^2$ and the out-of-sample MSE and $R^2$.


Toward answering the latter, we measure the prediction quality of the two models via data splitting:

1. Randomly split the data into one training sample and one testing sample. Here we just use a simple method (stratified splitting is a more sophisticated version of splitting that we might consider).
2. Use the training sample to estimate the parameters of the Basic Model and the Flexible Model.
3. Before using the testing sample, we evaluate in-sample fit.

We employ two different specifications for prediction:


1. **Basic Model**:   $X$ consists of a set of raw regressors (e.g. gender, experience, education indicators,  occupation and industry indicators and regional indicators).


2. **Flexible Model**:  $X$ consists of all raw regressors from the basic model plus a dictionary of transformations (e.g., ${exp}^2$ and ${exp}^3$) and additional two-way interactions of a polynomial in experience with other regressors. An example of a regressor created through a two-way interaction is *experience* times the indicator of having a *college degree*.

Using the **Flexible Model** enables us to approximate the real relationship by a more complex regression model and therefore to reduce the bias. The **Flexible Model** increases the range of potential shapes of the estimated regression function. In general, flexible models often deliver higher prediction accuracy but are harder to interpret.

In [4]:
#split the data into train and test sets
train, test = train_test_split(df, test_size=0.20, random_state=123)

In [6]:
#1. Basic Model using OLS 
model_base = 'lwage ~ sex + exp1 + shs + hsg+ scl + clg + mw + so + we + C(occ2) + C(ind2)'
base = smf.ols(model_base, data=train)
results_base = base.fit()
rsquared_base = results_base.rsquared
rsquared_adj_base = results_base.rsquared_adj
mse_base = np.mean(results_base.resid**2)
mse_adj_base = results_base.mse_resid
print(f'Rsquared={rsquared_base:.4f}')
print(f'Rsquared_adjusted={rsquared_adj_base:.4f}')
print(f'MSE={mse_base:.4f}')
print(f'MSE_adjusted={mse_adj_base:.4f}')

Rsquared=0.3176
Rsquared_adjusted=0.3092
MSE=0.2202
MSE_adjusted=0.2229

In [7]:
# 2. Flexible Model using OLS 
model_flex = ('lwage ~ sex + shs+hsg+scl+clg+C(occ2)+C(ind2)+mw+so+we '
              '+ (exp1+exp2+exp3+exp4)*(shs+hsg+scl+clg+C(occ2)+C(ind2)+mw+so+we)')
flex = smf.ols(model_flex, data=train)
results_flex = flex.fit()

rsquared_flex = results_flex.rsquared
rsquared_adj_flex = results_flex.rsquared_adj
mse_flex = np.mean(results_flex.resid**2)
mse_adj_flex = results_flex.mse_resid
print(f'Rsquared={rsquared_flex:.4f}')
print(f'Rsquared_adjusted={rsquared_adj_flex:.4f}')
print(f'MSE={mse_flex:.4f}')
print(f'MSE_adjusted={mse_adj_flex:.4f}')

Rsquared=0.3643
Rsquared_adjusted=0.3241
MSE=0.2051
MSE_adjusted=0.2181

### Re-estimating the Flexible Model using Lasso 

  >  *Lasso regression problem*: $$ \min_{b\in \mathbb{R}^p} \sum_{i=1}^n (Y_i - b\mathbf{X}_i')^2 + \lambda \cdot \sum_{j=1}^p |b_j|\hat{\psi}_j $$
    * First term is the OLS objective function
    * Second term is the penalty term: $\hat{\psi}$(*penalty loadings*), $\lambda$ (*penalty level*)

In [ ]:
# Lasso with cross-validation
X = flex.data.exog[:, 1:]  # exclude the intercept; we don't want the lasso to penalize the intercept
y = flex.data.endog
# train model using Lasso with cross validation and variable normalization
lasso = Pipeline([('scale', StandardScaler()),  # standardize the variables
                  ('lasso', lm.LassoCV())])
lasso.fit(X, y)
# verify the formulas
n, p = X.shape
p += 1
mse_lasso = np.mean((y - lasso.predict(X))**2)
mse_adj_lasso = mse_lasso * n / (n - p)
rsquared_lasso = 1 - mse_lasso / np.var(y)
rsquared_adj_lasso = 1 - mse_adj_lasso / np.var(y)
print(f'Rsquared={rsquared_lasso:.4f}')
print(f'Rsquared_adjusted={rsquared_adj_lasso:.4f}')
print(f'MSE={mse_lasso:.4f}')
print(f'MSE_adjusted={mse_adj_lasso:.4f}')

Rsquared=0.3309
Rsquared_adjusted=0.2885
MSE=0.2159
MSE_adjusted=0.2296

In [ ]:
#export the results in formatted tables 
res_df = pd.DataFrame()
res_df['Model'] = ['Basic reg', 'Flexible reg', 'Flexible Lasso']
res_df['p'] = [results_base.params.shape[0],
               results_flex.params.shape[0],
               results_flex.params.shape[0]]
res_df['R2'] = [rsquared_base, rsquared_flex, rsquared_lasso]
res_df['MSE'] = [mse_base, mse_flex, mse_lasso]
res_df['adj_R2'] = [rsquared_adj_base, rsquared_adj_flex, rsquared_adj_lasso]
res_df['adj_MSE'] = [mse_adj_base, mse_adj_flex, mse_adj_lasso]
res_df.head() # Show results

            Model    p        R2       MSE    adj_R2   adj_MSE
0       Basic reg   51  0.317622  0.220187  0.309237  0.222947
1    Flexible reg  246  0.364346  0.205110  0.324146  0.218135
2  Flexible Lasso  246  0.330946  0.215888  0.288461  0.229597

### Data Splitting and Out-of-Sample Prediction
Let's evaluate the model on the out-of-sample performance:

- Use the testing sample for evaluation. Predict the `wage`  of every observation in the testing sample based on the estimated parameters in the training sample.
  
- Calculate the Mean Squared Prediction Error `MSE` based on the testing sample for both prediction models.

In [ ]:
#Basic model: smf.ols to get the full data frame and evaluate out-of-sample performance 
tmp = smf.ols(model_base, data=df)  # just to extract df, not actually using this model
X_full = tmp.data.exog
y_full = tmp.data.endog
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=0.2, shuffle=True)
# estimating the parameters in the training sample
regbasic = sm.OLS(y_train, X_train).fit()
# predict out of sample
yhat_reg_base = regbasic.predict(X_test)
# calculating out-of-sample MSE
MSE_test1 = sum((y_test - yhat_reg_base)**2) / y_test.shape[0]
R2_test1 = 1. - MSE_test1 / np.var(y_test)
print("Test MSE for the basic model: " + str(MSE_test1)) #MSE_test is close to MSE_sample
print("Test R2 for the basic model: " + str(R2_test1))

Test MSE for the basic model: 0.23279677884486447
Test R2 for the basic model: 0.29923455136652233

In [12]:
#Flexible model: smf.ols to get the full data frame and evaluate out-of-sample performance
tmp = smf.ols(model_flex, data=df)  # just to extract df, not actually using this model
X_full = tmp.data.exog
y_full = tmp.data.endog
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=.2, shuffle=True)
# estimating the parameters in the training sample
regflex = sm.OLS(y_train, X_train).fit()
# predict out of sample
yhat_reg_flex = regflex.predict(X_test)
# calculating out-of-sample MSE
MSE_test2 = np.mean((y_test - yhat_reg_flex)**2)
R2_test2 = 1. - MSE_test2 / np.var(y_test)
print("Test MSE for the flexible model: " + str(MSE_test2))
print("Test R2 for the flexible model: " + str(R2_test2))

Test MSE for the flexible model: 0.23068665475502595
Test R2 for the flexible model: 0.27069156703210606

*  The discrepancy between the  $𝑀𝑆𝐸_{𝑡𝑒𝑠𝑡}$  and the  $𝑀𝑆𝐸_{𝑠𝑎𝑚𝑝𝑙𝑒}$  is not large.
*  The  $𝑀𝑆𝐸_{𝑡𝑒𝑠𝑡}$  vary across different data splits. Hence, it is a good idea *average the out-of-sample MSE* over different data splits to get valid results.
*  Based on the out-of-sample  $𝑀𝑆𝐸$ , the basic model using ols regression performs is about as well (or slightly better) than the flexible model.

In [13]:
# Lasso model with cross validation and variable normalization
lasso = Pipeline([('scale', StandardScaler()),  # standardize the variables
                  ('lasso', lm.LassoCV())])
lasso.fit(X_train[:, 1:], y_train)
# predict out of sample
yhat_test_lasso = lasso.predict(X_test[:, 1:])
# calculating out-of-sample MSE
MSE_test3 = np.mean((y_test - yhat_test_lasso)**2)
R2_test3 = 1. - MSE_test3 / np.var(y_test)
print("Test MSE for the basic model: " + str(MSE_test3))
print("Test R2 for the basic model: " + str(R2_test3))

Test MSE for the basic model: 0.2226355239791101
Test R2 for the basic model: 0.29614495780600314

In [16]:
# Store and display the full results 
res_df2 = pd.DataFrame()
res_df2['Model'] = ['Basic reg', 'Flexible reg', 'Flexible Lasso']
res_df2['MSE_{test}'] = [MSE_test1, MSE_test2, MSE_test3]
res_df2['R^2_{test}'] = [R2_test1, R2_test2, R2_test3]
# Show results
res_df2.head()

            Model  MSE_{test}  R^2_{test}
0       Basic reg    0.232797    0.299235
1    Flexible reg    0.230687    0.270692
2  Flexible Lasso    0.222636    0.296145

### Extra Flexible Model and Overfitting Problem 

It is not immediately clear why one would choose to use Lasso as results are fairly similar. To motivate, we consider an extra flexible model to show how OLS can overfit significantly to the in-sample train data and perform poorly on the out-of-sample testing data.

In [17]:
# Extra Flexible Model
model_extra = ('lwage ~ sex + (exp1+exp2+exp3+exp4+shs+hsg+scl+clg+C(occ2)+C(ind2)+mw+so+we)**2')
tmp = smf.ols(model_extra, data=df)  # just to extract df, not actually using this model
# In-sample fit
insamplefit = tmp.fit()
rsquared_ex = insamplefit.rsquared
rsquared_adj_ex = insamplefit.rsquared_adj
mse_ex = np.mean(insamplefit.resid**2)
mse_adj_ex = insamplefit.mse_resid
print(f'(In-sample) Rsquared={rsquared_ex :.4f}')
print(f'(In-sample) Rsquared_adjusted={rsquared_adj_ex :.4f}')
print(f'(In-sample) MSE={mse_ex :.4f}')
print(f'(In-sample) MSE_adjusted={mse_adj_ex:.4f}')

(In-sample) Rsquared=0.4489
(In-sample) Rsquared_adjusted=0.3506
(In-sample) MSE=0.1793
(In-sample) MSE_adjusted=0.2113

In [18]:
# Train test Split
X_full = tmp.data.exog
y_full = tmp.data.endog
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=.2, shuffle=True)
# estimating the parameters in the training sample
regextra = sm.OLS(y_train, X_train).fit()
# predict out of sample
yhat_reg_extra = regextra.predict(X_test)
# calculating out-of-sample MSE
MSE_test4 = np.mean((y_test - yhat_reg_extra)**2)
R2_test4 = 1. - MSE_test4 / np.var(y_test)
print("Test MSE for the flexible model: " + str(MSE_test4))
print("Test R2 for the flexible model: " + str(R2_test4))

Test MSE for the flexible model: 0.2785364364081525
Test R2 for the flexible model: 0.12455476343897687

In [19]:
# Lasso with cross validation and variable normalization
lasso = Pipeline([('scale', StandardScaler()),  # standardize the variables
                  ('lasso', lm.LassoCV())])
lasso.fit(X_train[:, 1:], y_train)
# predict in sample
yhat_train_lasso = lasso.predict(X_train[:, 1:])
# Calculate R-squared
R2_L = 1 - np.sum((yhat_train_lasso - y_train)**2) / np.sum((y_train - np.mean(y_train))**2)
# Calculate adjusted R-squared
pL = np.sum(lasso.named_steps['lasso'].coef_ != 0) #non-zero coefficients
ntrain = len(X_train)
baseline = np.sum((y_train - np.mean(y_train))**2) / (ntrain - 1)
R2_adjL = 1 - (np.sum((yhat_train_lasso - y_train)**2) / (ntrain - pL - 1)) / baseline
# Calculate Mean Squared Error (MSE)
lasso_res = y_train - yhat_train_lasso
MSEL = np.mean(lasso_res**2)
# Calculate adjusted MSE
MSE_adjL = (ntrain / (ntrain - pL - 1)) * MSEL
# Print the results
print("R-squared for the lasso with the extra flexible model (in-sample):", R2_L)
print("Adjusted R-squared for the extra flexible model (in-sample):", R2_adjL)
print("MSE for the lasso with the extra flexible model (in-sample):", MSEL)
print("Adjusted MSE for the lasso with the extra flexible model (in-sample):", MSE_adjL)

R-squared for the lasso with the extra flexible model (in-sample): 0.36342901615670054
Adjusted R-squared for the extra flexible model (in-sample): 0.32802770823922345
MSE for the lasso with the extra flexible model (in-sample): 0.20810799782725883
Adjusted MSE for the lasso with the extra flexible model (in-sample): 0.21973473886425074

In [20]:
# predict out of sample
yhat_test_lasso = lasso.predict(X_test[:, 1:])
# calculating out-of-sample MSE
MSE_test5 = np.mean((y_test - yhat_test_lasso)**2)
R2_test5 = 1. - MSE_test5 / np.var(y_test)
print("Test MSE for the basic model: " + str(MSE_test5))
print("Test R2 for the basic model: " + str(R2_test5))

Test MSE for the basic model: 0.21463246354955529
Test R2 for the basic model: 0.3254061470418239